In [1]:
import os
import pandas as pd

In [ ]:
def combine_data(folder_name, processed=0):

    full_input_path = os.path.join("original_curated/",folder_name)
    full_output_path = os.path.join("processed_data/", folder_name)

    if processed:
        full_input_path = folder_name

    if not os.path.exists(full_input_path):
        raise FileNotFoundError(f"Folder not found: {full_input_path}")


    print(f"Processing folder: {full_input_path}")
    print()
    # Step 1: List all CSV files
    csv_files = [f for f in os.listdir(full_input_path) if f.endswith('.csv')]
    print("CSV files found:")
    for f in csv_files:
        print(f)

    if not csv_files:
        raise ValueError(f"No CSV files found in {full_input_path}")

    # Step 2: Combine all CSV files
    df_list = []
    for f in csv_files:
        file_path = os.path.join(full_input_path, f)
        df = pd.read_csv(file_path)
        df_list.append(df)

    combined_df = pd.concat(df_list, ignore_index=True)
    
    if not processed:
        combined_df["Type"] = folder_name
    print()
    print(f"Number of rows after combination: {len(combined_df)}")

    # Step 3: Remove duplicates based on 'SMILES'
    if 'SMILES' not in combined_df.columns:
        raise KeyError("The column 'SMILES' is not present in the combined dataframe.")
    
    deduped_df = combined_df.drop_duplicates(subset='SMILES')
    print(f"Number of rows after removing duplicates based on 'SIMLES': {len(deduped_df)}")

    # Step 4: Reset index
    deduped_df.reset_index(drop=True, inplace=True)

    # Step 5: Save to CSV if output_path is provided

    deduped_df.to_csv(full_output_path + ".csv", index=False)
    print(f"Combined data saved to {full_output_path}.csv")

    return deduped_df

In [3]:
combined_train_DA = combine_data('train_with_data_augmentation')
combined_train_DA.tail(20)

Processing folder: original_curated/train_with_data_augmentation

CSV files found:
train4_DA_curated.csv
train3_DA_curated.csv
train2_DA_curated.csv
train5_DA_curated.csv
train7_DA_curated.csv
train8_DA_curated.csv
train9_DA_curated.csv
train1_DA_curated.csv
train10_DA_curated.csv
train6_DA_curated.csv

Number of rows after combination: 848836
Number of rows after removing duplicates based on 'SIMLES': 108380
Combined data saved to processed_data/train_with_data_augmentation.csv

,SMILES,MP,Type
108360,C=C(O)CC(O)=Nc1ccc(-c2ccc(NC(=O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation
108361,C=C(O)CC(O)=Nc1ccc(-c2ccc(NC(=O)CC(C)=O)c(C)c2...,212.0,train_with_data_augmentation
108362,C=C(O)CC(O)=Nc1ccc(-c2ccc(NC(O)=CC(C)=O)c(C)c2...,212.0,train_with_data_augmentation
108363,CC(=O)C=C(O)Nc1ccc(-c2ccc(N=C(O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation
108364,CC(=O)C=C(O)Nc1ccc(-c2ccc(N=C(O)CC(C)=O)c(C)c2...,212.0,train_with_data_augmentation
108365,CC(=O)C=C(O)Nc1ccc(-c2ccc(NC(=O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation
108366,CC(=O)C=C(O)Nc1ccc(-c2ccc(NC(=O)CC(C)=O)c(C)c2...,212.0,train_with_data_augmentation
108367,CC(=O)C=C(O)Nc1ccc(-c2ccc(NC(O)=CC(C)=O)c(C)c2...,212.0,train_with_data_augmentation
108368,CC(=O)CC(=O)Nc1ccc(-c2ccc(N=C(O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation
108369,CC(=O)CC(=O)Nc1ccc(-c2ccc(N=C(O)CC(C)=O)c(C)c2...,212.0,train_with_data_augmentation
108370,CC(=O)CC(=O)Nc1ccc(-c2ccc(NC(=O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation
108371,CC(=O)CC(O)=Nc1ccc(-c2ccc(N=C(O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation
108372,CC(=O)CC(O)=Nc1ccc(-c2ccc(N=C(O)CC(C)=O)c(C)c2...,212.0,train_with_data_augmentation
108373,CC(=O)CC(O)=Nc1ccc(-c2ccc(NC(=O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation
108374,CC(O)=CC(=O)Nc1ccc(-c2ccc(N=C(O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation
108375,CC(O)=CC(=O)Nc1ccc(-c2ccc(NC(=O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation
108376,CC(O)=CC(O)=Nc1ccc(-c2ccc(N=C(O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation
108377,CCCCCCCCCCCCCCCC(=O)OCCCC,16.9,train_with_data_augmentation
108378,[CH3][CH2][CH2][CH2][CH2][CH2][CH2][CH2][CH2][...,16.9,train_with_data_augmentation
108379,CCCCCCCCCCCCCCC=C(O)OCCCC,16.9,train_with_data_augmentation

In [4]:
combined_train = combine_data('train_without_data_augmentation')
combined_train.tail(20)

Processing folder: original_curated/train_without_data_augmentation

CSV files found:
train6_curated.csv
train3_curated.csv
train10_curated.csv
train9_curated.csv
train5_curated.csv
train2_curated.csv
train7_curated.csv
train4_curated.csv
train8_curated.csv
train1_curated.csv

Number of rows after combination: 137340
Number of rows after removing duplicates based on 'SIMLES': 17633
Combined data saved to processed_data/train_without_data_augmentation.csv

,SMILES,MP,Type
17613,S=C=Nc1ccc(cc1)N=C=S,131.0,train_without_data_augmentation
17614,COCCN1CCNCCC1,67.0,train_without_data_augmentation
17615,Brc1cnc(nc1OCc1ccccc1)N1CCOCC1,115.0,train_without_data_augmentation
17616,CCCCCCCC/C=C/CCCCCCCCN,25.0,train_without_data_augmentation
17617,O=C(N1CC(C=C1c1ccccc1)c1ccccc1)c1ccccc1,180.0,train_without_data_augmentation
17618,OC1OC(=O)c2c1cc(Cl)c(c2)Cl,180.0,train_without_data_augmentation
17619,C=CCC1(C(=O)NC(=S)NC1=O)C1CCCC=C1,148.0,train_without_data_augmentation
17620,S=C(C(=O)c1ccccc1)Nc1ccccc1Cl,119.0,train_without_data_augmentation
17621,CC1CCC(C1(C)C)(C)C(=O)O,106.0,train_without_data_augmentation
17622,O=C1C(C)CC(CC1=O)(C)C,91.0,train_without_data_augmentation
17623,Cc1nn(c(c1/C=N/OCc1ccc(cc1)C(=O)OC(C)(C)C)Oc1c...,102.0,train_without_data_augmentation
17624,Oc1cccc(c1)C(C)(C)C,45.0,train_without_data_augmentation
17625,Fc1ccccc1N1CCNCC1,46.0,train_without_data_augmentation
17626,O=C1N(c2c[nH]nc2)C(=O)c2c1cccc2,260.0,train_without_data_augmentation
17627,CCCNC(=O)C(C(F)(F)F)C(F)(F)F,106.0,train_without_data_augmentation
17628,[O-][N+](=O)CCO,-80.0,train_without_data_augmentation
17629,N#CCc1ccc(cc1)OC(=O)C,50.0,train_without_data_augmentation
17630,CCOC(=O)/C(=N\Nc1ccc(cc1)[N+](=O)[O-])/C(=O)C(...,184.0,train_without_data_augmentation
17631,O/N=C/1\C(=O)N(N=C1c1ccc(cc1)[N+](=O)[O-])c1cc...,223.0,train_without_data_augmentation
17632,Fc1cccc(n1)C(=O)O,141.0,train_without_data_augmentation

In [5]:
val = combine_data('val')
val.tail(20)

Processing folder: original_curated/val

CSV files found:
val9_curated.csv
val10_curated.csv
val5_curated.csv
val6_curated.csv
val3_curated.csv
val4_curated.csv
val8_curated.csv
val1_curated.csv
val2_curated.csv
val7_curated.csv

Number of rows after combination: 39250
Number of rows after removing duplicates based on 'SIMLES': 16193
Combined data saved to processed_data/val.csv

                                                  SMILES      MP Type
16173   C[SiH](O[Si](O[SiH](C)C)(O[SiH](C)C)O[SiH](C)C)C  -60.00  val
16174                                                CNN  -21.00  val
16175                                      CCCCNc1ccccc1  -14.40  val
16176                                  N#Cc1ccccc1C(=O)C   48.00  val
16177         ClCC1C(CCl)C2(C(C1(Cl)C(=C2Cl)Cl)(Cl)Cl)Cl  105.00  val
16178                                   Cc1ccc(c(c1)C)Cl  -32.50  val
16179                           OC(=O)c1sc(nc1C)c1cccnc1  246.00  val
16180                            CC(c1ccccc1)(c1ccccc1)O   80.00  val
16181                                      OC1=NCC(=N1)O  222.00  val
16182                                  Nc1cccc(c1)C(=O)C   96.00  val
16183  Oc1ccc2c(c1)CC[C@@H]1[C@@H]2CC[C@]2([C@H]1CCC2...  255.25  val
16184                                  CCCCCCCCCCC1CCCC1  -22.00  val
16185                           Clc1cccc(c1)[N+](=O)[O-]   45.00  val
16186                         O=S(=O)(c1ccccc1)Cc1ccccc1  149.00  val
16187                                              ClC#C -126.00  val
16188           N#C/C(=C\c1ccc(cc1)Cl)/c1scc(n1)c1ccccc1  104.00  val
16189            COC(=O)C1=C(C)NC(=C(C1c1ccco1)C(=O)OC)C  186.00  val
16190                                        Cc1csc(n1)S   88.00  val
16191               CC(c1cc(cc(c1)C(C)(C)C)C(C)(C)C)(C)C   71.00  val
16192                              OB(c1ccccc1C(F)(F)F)O  109.00  val

In [6]:
test = combine_data('test_predictions')
test.tail(20)

Processing folder: original_curated/test_predictions

CSV files found:
consensus_without_data_augmentation.csv
consensus_with_data_augmentation_curated.csv

Number of rows after combination: 3922
Number of rows after removing duplicates based on 'SIMLES': 1961
Combined data saved to processed_data/test_predictions.csv

,SMILES,exp MP,GNN1,GNN2,GNN3,GNN4,GNN5,GNN6,GNN7,GNN8,GNN9,GNN10,Consensus,SD,Mpexp,Type
1941,COc1ccc(cc1/C=C/C(=O)n1cnc2c1ncnc2N)OC,261.00,215.51,235.77,220.82,221.63,201.20,254.14,229.25,247.40,215.80,235.22,227.67,15.13,NaN,test_predictions
1942,O=C1C=COC1C,18.00,67.28,74.81,46.64,38.25,61.34,78.95,83.65,44.24,33.97,78.46,60.76,17.62,NaN,test_predictions
1943,Clc1ccccc1C(=O)c1ccccc1,46.00,39.16,43.85,47.88,51.99,54.63,31.88,44.65,52.50,30.10,43.70,44.03,7.92,NaN,test_predictions
1944,CC(=O)c1ccc(c(c1)C)C,-3.00,29.94,31.09,47.96,35.00,23.25,25.47,43.78,48.89,27.89,19.65,33.29,9.82,NaN,test_predictions
1945,Nc1cccc(c1)S(=O)(=O)N,141.00,156.66,116.49,173.28,142.28,164.78,144.47,152.44,135.50,144.96,159.84,149.07,15.32,NaN,test_predictions
1946,CCOC(=O)Cn1cnc(=O)c2c1ncn2CC(=O)OCC,139.85,129.39,142.86,124.66,162.37,182.31,137.24,129.16,166.28,145.06,158.10,147.74,17.93,NaN,test_predictions
1947,ClC(=O)c1ccc(c(c1F)C)F,37.00,7.14,8.64,24.16,34.69,3.02,10.46,27.30,30.44,11.00,29.74,18.66,11.08,NaN,test_predictions
1948,OC(=O)c1cccnc1Nc1cccc(c1C)Cl,234.00,211.89,248.31,211.69,222.82,227.83,225.64,257.93,260.63,221.58,276.68,236.50,21.49,NaN,test_predictions
1949,CCCCCCCC=O,13.00,-16.39,-37.65,-28.81,-24.06,-35.07,-28.47,-25.97,-42.15,-16.91,-27.24,-28.27,7.88,NaN,test_predictions
1950,Brc1ccc(c(c1)C(F)(F)F)O,84.00,76.72,69.58,62.06,59.48,58.13,66.55,65.36,77.90,72.83,59.08,66.77,6.92,NaN,test_predictions
1951,CCCC#CCCCC(=O)O,-3.00,-2.58,5.15,-3.09,0.60,-0.83,-13.39,13.82,-5.75,16.04,-12.67,-0.27,9.30,NaN,test_predictions
1952,CC(=O)OCC(OC(=O)C)C,-31.00,-43.48,-30.02,-54.70,-59.99,-26.44,-36.41,-28.99,-24.89,1.65,-53.39,-35.66,17.32,NaN,test_predictions
1953,C#CC1(O)CCC2C1(C)CCC1C2CCc2c1ccc(c2)OC1CCCC1,107.50,130.06,112.83,151.79,69.22,145.83,118.62,126.65,147.76,110.92,163.36,127.70,25.68,NaN,test_predictions
1954,COc1ccc(cc1)Nc1nc(N)nnc1c1ccccc1,293.00,186.88,196.55,231.84,206.45,188.37,208.26,222.60,225.53,203.27,202.75,207.25,14.49,NaN,test_predictions
1955,OC(=O)Cc1ccc(c(c1)F)F,49.00,82.06,92.17,87.89,75.43,71.99,86.19,76.60,107.53,69.87,91.87,84.16,10.85,NaN,test_predictions
1956,CCOC(=O)N(c1ccccc1)c1ccccc1,72.00,62.50,83.14,52.31,48.03,67.88,64.15,51.38,71.16,63.83,64.20,62.86,9.86,NaN,test_predictions
1957,CC(C(c1ccccc1)C(C)C)C,-24.50,-18.08,-3.62,-3.55,-55.66,-5.14,-68.88,3.81,27.80,23.58,-21.78,-12.15,29.26,NaN,test_predictions
1958,OC(=O)Cc1ccc(c(c1)Cl)Cl,90.00,100.64,109.64,105.56,126.81,99.12,103.35,101.24,130.85,116.05,113.57,110.68,10.53,NaN,test_predictions
1959,CCCOC(=O)c1cc(O)c(c(c1)O)O,148.00,101.46,112.88,89.95,133.71,100.77,92.07,107.38,111.35,122.40,117.72,108.97,12.90,NaN,test_predictions
1960,O=C1NC(=O)NC1(C1CCC1)c1ccccc1,235.00,170.96,180.08,175.50,173.28,195.17,195.51,221.30,159.80,220.96,180.12,187.27,19.70,NaN,test_predictions

In [7]:
processed_all = combine_data('processed_data', processed=1)
processed_all.tail(20)

Processing folder: processed_data

CSV files found:
val.csv
test_predictions.csv
train_without_data_augmentation.csv
train_with_data_augmentation.csv

Number of rows after combination: 144167
Number of rows after removing duplicates based on 'SIMLES': 110355
Combined data saved to processed_data/processed_data.csv

,SMILES,MP,Type,exp MP,GNN1,GNN2,GNN3,GNN4,GNN5,GNN6,GNN7,GNN8,GNN9,GNN10,Consensus,SD,Mpexp
110335,C=C(O)CC(O)=Nc1ccc(-c2ccc(N=C(O)CC(C)=O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110336,C=C(O)CC(O)=Nc1ccc(-c2ccc(NC(=O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110337,C=C(O)CC(O)=Nc1ccc(-c2ccc(NC(=O)CC(C)=O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110338,C=C(O)CC(O)=Nc1ccc(-c2ccc(NC(O)=CC(C)=O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110339,CC(=O)C=C(O)Nc1ccc(-c2ccc(N=C(O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110340,CC(=O)C=C(O)Nc1ccc(-c2ccc(N=C(O)CC(C)=O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110341,CC(=O)C=C(O)Nc1ccc(-c2ccc(NC(=O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110342,CC(=O)C=C(O)Nc1ccc(-c2ccc(NC(=O)CC(C)=O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110343,CC(=O)C=C(O)Nc1ccc(-c2ccc(NC(O)=CC(C)=O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110344,CC(=O)CC(=O)Nc1ccc(-c2ccc(N=C(O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110345,CC(=O)CC(=O)Nc1ccc(-c2ccc(N=C(O)CC(C)=O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110346,CC(=O)CC(=O)Nc1ccc(-c2ccc(NC(=O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110347,CC(=O)CC(O)=Nc1ccc(-c2ccc(N=C(O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110348,CC(=O)CC(O)=Nc1ccc(-c2ccc(N=C(O)CC(C)=O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110349,CC(=O)CC(O)=Nc1ccc(-c2ccc(NC(=O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110350,CC(O)=CC(=O)Nc1ccc(-c2ccc(N=C(O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110351,CC(O)=CC(=O)Nc1ccc(-c2ccc(NC(=O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110352,CC(O)=CC(O)=Nc1ccc(-c2ccc(N=C(O)C=C(C)O)c(C)c2...,212.0,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110353,[CH3][CH2][CH2][CH2][CH2][CH2][CH2][CH2][CH2][...,16.9,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110354,CCCCCCCCCCCCCCC=C(O)OCCCC,16.9,train_with_data_augmentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
processed_all["SMILES"].nunique()

110355