In [1]:
#Importing all the relevant libraries
import os
import pandas as pd
from pathlib import Path
from collections import defaultdict

In [2]:
#Set all the file paths
#processed_data_embeddings = file that Nasim sent us 
#original curated = duplicate of folder structure of original datasets
#target root = where the original datasets + embeddings coloumn will be exported 

# 1) Define the base folder *relative* to your notebook/script
BASE = Path.cwd().parent
print(BASE)

# 2) Import the test file
test_file_dir = BASE / "data_curation" / "original_curated" / "test_predictions" / "consensus_without_data_augmentation.csv"

# 3) Load dataframe 
test_df = pd.read_csv(test_file_dir)
test_df.info()
print(test_df.isna().sum())

master_path = BASE / "data_curation" / "import_embeddings" / "processed_data_embeddings.csv"
source_root = BASE / "data_curation" / "original_curated"
target_root = BASE / "data_curation" / "original_curated_with_embeddings_and_MW"

/Users/sdl5_mp/Documents/GitHub/SDL5_MP
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1961 entries, 0 to 1960
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   SMILES     1961 non-null   object
 1   exp MP     1961 non-null   float64
 2   GNN1       1961 non-null   float64
 3   GNN2       1961 non-null   float64
 4   GNN3       1961 non-null   float64
 5   GNN4       1961 non-null   float64
 6   GNN5       1961 non-null   float64
 7   GNN6       1961 non-null   float64
 8   GNN7       1961 non-null   float64
 9   GNN8       1961 non-null   float64
 10  GNN9       1961 non-null   float64
 11  GNN10      1961 non-null   float64
 12  Consensus  1961 non-null   float64
 13  SD         1961 non-null   float64
dtypes: float64(13), object(1)
memory usage: 214.6+ KB
SMILES       0
exp MP       0
GNN1         0
GNN2         0
GNN3         0
GNN4         0
GNN5         0
GNN6         0
GNN7         0
GNN8         0
GNN9         0
GNN10        0
Consensus    0
SD           0
dtype: int64

In [3]:
#Load the processed embeddings file
master_df = pd.read_csv(master_path)
# Zip maps SMILES with embedding, and dict turns it into dictionary
embedding_dict = dict(zip(master_df["SMILES"], master_df["embeddings"]))
#Check the length of the dictionary to see if they all were imported 
print(len(embedding_dict)) #Python can do this by itself, instead of printing and the user checking if the rows on the excel file match the printed number, just tell python to see if the 2 numbers match, if True continute
#Check the first 10 items to see if they are accurate, and see if any SMILES were duplicated
duplicate_count = master_df["SMILES"].duplicated().sum()
print(duplicate_count)
print(master_df["embeddings"].isna().sum())
list(embedding_dict.items())[:5]

110355
0
33

[('FC1=CC=CC(F)=C1',
  'tensor([7.4845e-01, 9.7289e-01, 2.9506e-01, 5.4976e-01, 0.0000e+00, 7.2295e-03,\n        0.0000e+00, 4.2419e-01, 2.0893e-01, 3.4361e-02, 4.5029e-02, 1.8573e-01,\n        0.0000e+00, 2.6957e-01, 0.0000e+00, 9.1086e-03, 0.0000e+00, 0.0000e+00,\n        1.2670e+00, 0.0000e+00, 0.0000e+00, 8.0744e-01, 3.6756e-02, 2.8403e-01,\n        0.0000e+00, 1.1282e-01, 1.0391e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        0.0000e+00, 0.0000e+00, 0.0000e+00, 1.7266e-03, 0.0000e+00, 4.2105e-01,\n        9.4307e-02, 7.9049e-01, 5.5309e-01, 2.1838e-01, 7.0057e-01, 0.0000e+00,\n        1.3898e-01, 0.0000e+00, 5.4405e-01, 1.7825e-01, 0.0000e+00, 3.4705e-01,\n        0.0000e+00, 0.0000e+00, 3.6744e-01, 1.2772e-01, 9.3602e-01, 7.2442e-01,\n        0.0000e+00, 0.0000e+00, 6.8162e-01, 4.2956e-01, 2.9862e-01, 0.0000e+00,\n        1.6079e-01, 4.3156e-01, 3.9458e-01, 3.3769e-01, 0.0000e+00, 0.0000e+00,\n        2.0086e-01, 0.0000e+00, 2.0586e-02, 0.0000e+00, 1.4934e-02, 2.2698e-01,\n        1.8502e-01, 6.5402e-01, 8.3770e-02, 0.0000e+00, 3.4724e-01, 7.4019e-01,\n        9.0356e-02, 0.0000e+00, 2.0655e-01, 1.4284e-01, 0.0000e+00, 2.5619e-01,\n        0.0000e+00, 1.0481e-01, 1.1052e-01, 5.4355e-02, 9.3161e-02, 4.9751e-01,\n        2.2000e-01, 1.1698e-01, 2.9619e-01, 5.2050e-01, 2.5584e-01, 0.0000e+00,\n        4.2073e-01, 0.0000e+00, 8.4462e-02, 8.8399e-02, 2.0184e-01, 1.8021e-01,\n        2.4832e-01, 4.5314e-02, 5.1100e-01, 7.4511e-02, 3.9623e-02, 1.9134e-02,\n        2.9679e-01, 4.0879e-01, 0.0000e+00, 1.8342e-01, 5.3659e-02, 1.0031e-01,\n        5.7599e-02, 0.0000e+00, 6.5195e-01, 7.9455e-02, 5.7668e-02, 0.0000e+00,\n        4.5390e-01, 0.0000e+00, 3.2622e-01, 0.0000e+00, 0.0000e+00, 4.9421e-01,\n        8.2083e-01, 0.0000e+00, 8.3587e-02, 5.7633e-02, 2.6519e+00, 6.0822e-01,\n        2.6944e-01, 1.9350e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 8.8434e-03,\n        0.0000e+00, 5.9529e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.3789e-01,\n        1.6055e-01, 0.0000e+00, 7.7563e-02, 4.4423e-01, 0.0000e+00, 3.4167e-01,\n        5.5055e-01, 0.0000e+00, 1.2999e-01, 6.3074e-01, 1.6547e-01, 0.0000e+00,\n        0.0000e+00, 3.2996e-01, 0.0000e+00, 4.4989e-01, 1.8533e-01, 0.0000e+00,\n        6.6901e-01, 1.7263e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        0.0000e+00, 0.0000e+00, 7.2392e-03, 1.6454e-01, 2.2379e-01, 3.5222e-02,\n        3.8943e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        7.3556e-01, 0.0000e+00, 1.6433e-01, 2.2555e-01, 1.8179e-01, 2.5297e-01,\n        5.1181e-01, 0.0000e+00, 4.6735e-01, 6.4850e-01, 3.0563e-01, 2.3850e-01,\n        8.5131e-01, 0.0000e+00, 1.3002e-02, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        0.0000e+00, 1.2650e+00, 0.0000e+00, 0.0000e+00, 1.6385e-01, 5.1998e-01,\n        2.0409e-01, 0.0000e+00, 3.5500e-01, 1.7590e-01, 0.0000e+00, 0.0000e+00,\n        1.0917e-01, 0.0000e+00, 6.0735e-02, 6.5840e-01, 0.0000e+00, 0.0000e+00,\n        0.0000e+00, 5.1529e-01, 8.1942e-02, 2.8453e-01, 1.5674e-01, 0.0000e+00,\n        0.0000e+00, 7.6264e-02, 0.0000e+00, 5.4169e-01, 5.5931e-01, 0.0000e+00,\n        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        0.0000e+00, 0.0000e+00, 5.2824e-01, 0.0000e+00, 1.5090e-04, 4.7120e-01,\n        1.4512e-01, 0.0000e+00, 0.0000e+00, 8.4371e-02, 0.0000e+00, 0.0000e+00,\n        1.6465e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 5.6633e-01, 0.0000e+00,\n        0.0000e+00, 5.1517e-01, 0.0000e+00, 0.0000e+00, 4.9996e-01, 5.5811e-01,\n        0.0000e+00, 0.0000e+00, 9.5449e-01, 0.0000e+00, 5.9333e-01, 1.3674e+00,\n        0.0000e+00, 3.7167e-01, 0.0000e+00, 1.0838e-01, 0.0000e+00, 0.0000e+00,\n        0.0000e+00, 7.6267e-02, 0.0000e+00, 4.5640e-01, 0.0000e+00, 0.0000e+00,\n        2.5659e-01, 0.0000e+00, 7.1894e-03, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        0.0000e+00, 0.0000e+00, 0.0000e+00, 1.3451e-01, 0.0000e+00, 0.0000e+00,\n        4.3144e-01, 0.0000e+00, 1.6031e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        3.4204e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 9.5816e-02, 0.0000e+00,\n        6.8032e-01, 9.0553e-02, 6.8001e-02, 3.1914e-01, 3.2792e-02, 6.0164e-01,\n        0.0000e+00, 0.0000e+00, 1.5579e-01, 0.0000e+00, 2.6684e+00, 1.0531e-01,\n        2.9679e-01, 1.9530e-01, 7.1156e-01, 0.0000e+00, 2.6564e-02, 8.9795e-02,\n        0.0000e+00, 4.5658e-01, 4.9070e-02, 0.0000e+00, 3.8186e-01, 6.2401e-02,\n        3.8466e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.5452e-01, 1.4212e-01,\n        0.0000e+00, 0.0000e+00, 1.5848e-01, 0.0000e+00, 0.0000e+00, 1.5303e-01,\n        0.0000e+00, 0.0000e+00, 6.2051e-01, 0.0000e+00, 0.0000e+00, 3.4120e-01,\n        0.0000e+00, 4.2561e-01, 0.0000e+00, 5.0847e-01, 6.3478e-02, 0.0000e+00,\n        0.0000e+00, 4.2927e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 3.7141e-01,\n        1.6152e+00, 3.2521e-02, 0.0000e+00, 0.0000e+00, 5.0974e-01, 1.5957e-01,\n        0.0000e+00, 0.0000e+00, 0.0000e+00, 2.7326e-01, 3.6379e-01, 6.7371e-01,\n        2.0158e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 7.3358e-03, 1.0769e+00,\n        2.0505e-01, 0.0000e+00, 1.5668e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        0.0000e+00, 0.0000e+00, 0.0000e+00, 1.9580e-01, 0.0000e+00, 1.0453e-01,\n        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 6.9587e-01, 3.0506e-01,\n        0.0000e+00, 2.1859e-03, 2.1816e-01, 1.7141e-02, 1.5904e-01, 0.0000e+00,\n        0.0000e+00, 5.7515e-01, 7.0643e-01, 0.0000e+00, 0.0000e+00, 5.5321e-01,\n        0.0000e+00, 1.5593e-01, 1.7431e+00, 0.0000e+00, 4.2132e-01, 1.6947e-01,\n        5.5210e-01, 2.4494e-02, 7.6870e-01, 2.2333e-01, 0.0000e+00, 0.0000e+00,\n        2.2001e-01, 3.2503e-03, 3.1545e-01, 0.0000e+00, 0.0000e+00, 8.8353e-01,\n        0.0000e+00, 3.4510e-01, 0.0000e+00, 3.3257e-01, 0.0000e+00, 0.0000e+00,\n        1.0853e+00, 0.0000e+00, 1.3904e+00, 0.0000e+00, 0.0000e+00, 1.6951e-01,\n        3.4437e-01, 6.5265e-03, 8.8891e-01, 0.0000e+00, 1.2552e-02, 1.1900e+00,\n        0.0000e+00, 0.0000e+00, 1.5008e-01, 6.6247e-02, 1.5162e-01, 4.8721e-01,\n        1.8499e-01, 0.0000e+00, 7.1811e-02, 1.9635e-01, 2.8412e-01, 0.0000e+00,\n        7.1140e-01, 7.5192e-01, 0.0000e+00, 8.2701e-01, 2.9843e-01, 0.0000e+00,\n        0.0000e+00, 0.0000e+00, 4.1383e-01, 1.8576e-01, 0.0000e+00, 1.2356e+00,\n        0.0000e+00, 1.4463e-01, 0.0000e+00, 2.3627e-02, 4.0325e-02, 0.0000e+00,\n        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 3.9288e-01, 2.9831e-01,\n        0.0000e+00, 5.2498e-01, 0.0000e+00, 2.1196e-01, 0.0000e+00, 5.4229e-01,\n        0.0000e+00, 1.2886e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        1.4069e-01, 0.0000e+00, 0.0000e+00, 1.7242e-01, 0.0000e+00, 0.0000e+00,\n        1.2140e+00, 0.0000e+00, 0.0000e+00, 3.0579e-01, 1.7147e-01, 0.0000e+00,\n        3.8382e-01, 0.0000e+00, 3.9518e-01, 1.9165e-02, 0.0000e+00, 2.8274e-01,\n        4.2101e-01, 0.0000e+00, 2.4004e-01, 3.4387e-01, 9.0937e-02, 0.0000e+00,\n        7.8775e-01, 0.0000e+00])'),
 ('Fc1cccc(F)c1',
  'tensor([2.0658e-01, 0.0000e+00, 0.0000e+00, 4.7508e-01, 0.0000e+00, 0.0000e+00,\n        3.0385e-01, 4.8824e-01, 1.6776e-01, 6.4959e-01, 0.0000e+00, 0.0000e+00,\n        2.3959e-01, 2.0282e-01, 0.0000e+00, 0.0000e+00, 3.2316e-01, 0.0000e+00,\n        1.6798e-01, 0.0000e+00, 3.8050e-01, 2.9221e-01, 1.3101e-01, 3.3321e-01,\n        5.3543e-01, 0.0000e+00, 1.3807e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        3.2385e-02, 0.0000e+00, 2.2779e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        7.2105e-01, 3.0615e+00, 2.1849e-01, 1.6694e-02, 1.9341e-02, 8.6369e-02,\n        0.0000e+00, 2.2952e-01, 5.5954e-01, 3.1324e-02, 2.7847e-01, 0.0000e+00,\n        3.8442e-01, 4.2206e-01, 3.5609e-01, 0.0000e+00, 1.3371e+00, 0.0000e+00,\n        1.5110e+00, 2.6633e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 7.7738e-02,\n        2.0047e-01, 9.0874e-02, 3.1037e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        3.9635e-01, 0.0000e+00, 4.3108e-02, 0.0000e+00, 1.9350e-01, 2.9702e-01,\n        1.1642e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 9.8270e-01,\n        0.0000e+00, 2.5316e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        0.0000e+00, 0.0000e+00, 3.0545e-01, 3.2579e-01, 5.2781e-01, 0.0000e+00,\n        2.5921e-02, 4.1499e-03, 3.7039e-01, 7.5825e-01, 7.6800e-01, 1.1591e-01,\n        4.4928e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 6.0420e-01, 9.2773e-01,\n        0.0000e+00, 2.7325e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 4.8944e-01,\n        4.9574e-01, 2.7495e-01, 5.1860e-01, 0.0000e+00, 2.6767e-01, 0.0000e+00,\n        0.0000e+00, 0.0000e+00, 9.5215e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        1.3056e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 7.1893e-02, 1.8936e-01,\n        1.5937e-01, 4.1047e-02, 5.1889e-01, 0.0000e+00, 3.2751e-02, 0.0000e+00,\n        0.0000e+00, 3.0095e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 3.1268e-01,\n        0.0000e+00, 0.0000e+00, 0.0000e+00, 1.6310e-02, 0.0000e+00, 1.6105e-01,\n        3.4562e-01, 3.5555e-02, 3.9988e-01, 4.5394e-01, 0.0000e+00, 0.0000e+00,\n        0.0000e+00, 9.8670e-02, 9.7579e-03, 1.6887e-01, 1.6090e-01, 1.7270e-03,\n        0.0000e+00, 3.2115e-02, 0.0000e+00, 1.4788e-01, 2.5079e-01, 0.0000e+00,\n        7.7689e-01, 8.2263e-01, 5.2951e-01, 3.8973e-01, 1.2300e+00, 3.7566e-01,\n        1.3959e+00, 5.2987e-02, 6.9162e-01, 0.0000e+00, 2.9788e-01, 0.0000e+00,\n        2.7079e-01, 0.0000e+00, 4.4905e-01, 0.0000e+00, 5.0197e-01, 3.7563e-01,\n        4.8909e-01, 4.8153e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.6195e-01,\n        3.1069e-01, 3.1133e-01, 0.0000e+00, 5.8701e-01, 2.2797e+00, 6.4031e-01,\n        9.2758e-01, 0.0000e+00, 3.0159e-01, 3.2999e-02, 1.5768e-01, 4.4197e-01,\n        8.4460e-01, 0.0000e+00, 3.2354e-01, 3.9636e-01, 0.0000e+00, 1.0366e-01,\n        0.0000e+00, 0.0000e+00, 3.0508e-01, 4.7878e-01, 0.0000e+00, 0.0000e+00,\n        2.2620e-01, 0.0000e+00, 4.5603e-01, 0.0000e+00, 5.2881e-01, 0.0000e+00,\n        0.0000e+00, 3.2881e-01, 3.7167e-01, 0.0000e+00, 9.6390e-01, 3.4057e-01,\n        1.9324e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        3.1150e-02, 5.8676e-01, 9.4730e-01, 0.0000e+00, 3.2440e-01, 3.6070e-01,\n        0.0000e+00, 0.0000e+00, 9.3194e-01, 0.0000e+00, 0.0000e+00, 1.0664e+00,\n        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 9.2439e-02,\n        5.5101e-01, 0.0000e+00, 3.5238e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        1.7990e+00, 4.4121e-01, 0.0000e+00, 3.2061e-01, 0.0000e+00, 7.0445e-01,\n        2.9796e-01, 0.0000e+00, 1.0854e-01, 0.0000e+00, 3.2170e-01, 1.0528e+00,\n        0.0000e+00, 0.0000e+00, 1.6449e+00, 2.9320e-01, 0.0000e+00, 0.0000e+00,\n        4.4476e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        4.8595e-01, 2.1611e-01, 4.5413e-01, 4.7560e-01, 4.0710e-01, 0.0000e+00,\n        0.0000e+00, 0.0000e+00, 0.0000e+00, 6.5277e-01, 8.4743e-03, 0.0000e+00,\n        0.0000e+00, 0.0000e+00, 0.0000e+00, 1.3146e-01, 0.0000e+00, 0.0000e+00,\n        1.6806e-01, 3.4243e-01, 1.5152e-02, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        3.2420e-02, 4.7270e-02, 1.6592e-02, 0.0000e+00, 8.8985e-02, 0.0000e+00,\n        8.5241e-02, 6.8156e-01, 0.0000e+00, 0.0000e+00, 9.1130e-02, 0.0000e+00,\n        0.0000e+00, 2.6980e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        7.8924e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.3297e-01, 1.5386e-01,\n        5.9660e-01, 6.3182e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 3.0465e-01,\n        0.0000e+00, 4.2495e-01, 2.4507e-01, 3.2553e-01, 1.1530e-01, 0.0000e+00,\n        0.0000e+00, 1.4348e-01, 2.3193e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00,\n        5.3190e-01, 9.1333e-01, 0.0000e+00, 3.3955e-01, 0.0000e+00, 2.1784e-02,\n        2.8450e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.3776e+00, 0.0000e+00,\n        0.0000e+00, 3.6129e-01, 9.9951e-02, 0.0000e+00, 0.0000e+00, 3.3897e-01,\n        0.0000e+00, 0.0000e+00, 0.0000e+00, 5.6922e-01, 2.6101e-01, 0.0000e+00,\n        3.9518e-01, 0.0000e+00, 1.6666e-01, 0.0000e+00, 1.0113e-01, 4.6709e-01,\n        3.2515e-01, 0.0000e+00, 2.5239e-01, 1.2862e-01, 0.0000e+00, 6.9123e-02,\n        3.9887e-02, 0.0000e+00, 0.0000e+00, 1.1433e-02, 6.9928e-01, 0.0000e+00,\n        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.8000e-01, 3.1250e-01,\n        0.0000e+00, 1.7660e-01, 0.0000e+00, 0.0000e+00, 1.9439e-02, 0.0000e+00,\n        0.0000e+00, 0.0000e+00, 1.2281e-01, 0.0000e+00, 1.1842e-01, 0.0000e+00,\n        0.0000e+00, 2.5181e-01, 5.8719e-01, 3.6235e-01, 1.0916e-01, 5.5205e-02,\n        0.0000e+00, 0.0000e+00, 7.0504e-01, 2.8684e-01, 0.0000e+00, 1.6565e+00,\n        1.3766e-01, 2.7949e-01, 2.8610e-01, 0.0000e+00, 5.7578e-01, 8.1552e-01,\n        0.0000e+00, 1.4822e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.6890e-01,\n        0.0000e+00, 0.0000e+00, 0.0000e+00, 4.1670e-02, 0.0000e+00, 1.3512e-01,\n        0.0000e+00, 2.7018e-01, 2.2866e-01, 0.0000e+00, 0.0000e+00, 1.6883e-01,\n        0.0000e+00, 0.0000e+00, 8.1143e-01, 0.0000e+00, 1.6435e+00, 7.5208e-01,\n        0.0000e+00, 0.0000e+00, 5.5838e-01, 0.0000e+00, 6.0332e-01, 0.0000e+00,\n        1.1394e+00, 0.0000e+00, 0.0000e+00, 3.1010e-01, 3.9326e-01, 1.6527e-01,\n        0.0000e+00, 3.4271e-01, 7.4555e-02, 0.0000e+00, 4.0276e-01, 2.8484e-01,\n        0.0000e+00, 0.0000e+00, 0.0000e+00, 3.6843e-01, 8.2720e-01, 7.5082e-01,\n        5.6665e-01, 7.1030e-02, 4.0141e-01, 0.0000e+00, 3.4014e-01, 2.9432e-01,\n        0.0000e+00, 0.0000e+00, 4.3528e-01, 0.0000e+00, 0.0000e+00, 6.9358e-01,\n        8.5962e-01, 0.0000e+00, 5.9445e-01, 5.9503e-02, 4.1487e-01, 4.8410e-03,\n        4.9646e-01, 3.9142e-01, 0.0000e+00, 0.0000e+00, 3.3717e-01, 0.0000e+00,\n        1.0387e-01, 0.0000e+00, 0.0000e+00, 4.3752e-01, 3.4572e-01, 6.3813e-01,\n        3.1276e-01, 0.0000e+00, 0.0000e+00, 2.5277e-01, 0.0000e+00, 5.5661e-01,\n        1.2615e-01, 7.6921e-01, 3.3683e-01, 0.0000e+00, 8.5428e-01, 0.0000e+00,\n        0.0000e+00, 0.0000e+00])'),
 ('[F][c]1[cH][cH][cH][c]([F])[cH]1',
  'tensor([0.0000, 0.7680, 0.0845, 0.7542, 0.0000, 0.0000, 0.0000, 0.0000, 0.1766,\n        0.7646, 0.0000, 0.0000, 0.0000, 0.0000, 0.2158, 0.0541, 0.0597, 0.0442,\n        0.7890, 0.0000, 0.0000, 2.0646, 0.0000, 0.0713, 0.0000, 0.0000, 0.0000,\n        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,\n        0.5613, 2.7463, 0.3014, 0.0000, 0.0000, 0.0185, 0.0000, 0.2030, 0.5227,\n        0.4492, 0.3363, 0.2439, 0.6399, 0.0870, 0.0000, 0.0000, 0.7156, 0.0000,\n        0.4975, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.6083, 0.0000, 0.0000,\n        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1799, 0.2023, 0.1657, 0.2747,\n        0.2154, 0.0000, 0.0000, 0.0000, 0.0000, 0.2035, 0.0000, 0.1482, 0.5018,\n        0.1993, 0.0000, 0.0000, 0.0000, 0.0000, 0.0916, 0.0735, 0.5866, 0.0000,\n        0.1452, 0.0000, 0.0000, 0.0678, 0.6169, 0.0000, 0.5156, 0.1434, 0.0000,\n        0.0000, 0.7840, 0.3878, 0.0000, 0.0372, 0.0000, 0.0000, 0.0516, 0.5687,\n        0.9373, 0.0000, 0.0000, 0.7861, 0.1253, 0.0000, 0.0000, 0.0000, 0.6791,\n        0.0000, 0.0000, 0.0000, 0.0684, 0.3144, 0.4256, 0.2274, 0.0167, 0.6044,\n        0.4255, 0.3062, 0.0000, 0.0000, 0.7486, 0.7839, 0.0447, 0.0000, 0.0000,\n        0.0000, 0.0000, 0.4193, 0.0000, 0.1581, 0.0000, 0.0000, 0.0000, 0.1972,\n        0.3687, 0.5300, 0.4449, 0.3549, 0.0000, 0.0000, 0.0000, 0.1630, 0.0000,\n        0.0000, 0.1373, 0.0000, 0.3892, 0.0000, 0.2865, 0.3534, 0.6982, 0.0000,\n        0.6393, 0.2166, 0.3551, 0.0000, 0.2535, 0.0755, 0.0000, 0.3973, 0.3067,\n        0.1035, 0.2225, 0.5821, 0.1902, 0.0000, 0.2674, 0.1496, 0.0000, 0.6453,\n        0.3981, 0.8920, 0.2479, 0.2613, 0.3069, 0.5541, 0.1488, 0.1722, 0.0000,\n        0.5977, 0.5648, 0.9580, 0.7719, 0.0000, 0.0000, 1.0247, 0.4256, 0.0169,\n        0.2851, 0.0000, 1.2689, 0.0731, 0.0000, 0.0000, 0.3741, 0.0000, 0.0948,\n        0.2321, 0.1097, 0.0000, 0.2680, 0.4425, 0.8837, 0.0000, 0.4950, 0.0000,\n        0.7745, 0.5445, 0.4566, 0.2913, 0.4786, 0.3696, 0.0000, 0.7707, 0.1940,\n        0.0000, 0.0000, 0.2479, 0.2024, 0.4035, 0.0000, 0.0000, 0.4291, 0.0000,\n        0.0000, 0.0000, 0.1655, 0.3415, 0.0000, 0.4692, 0.7091, 0.0000, 0.0000,\n        0.0000, 0.0000, 0.4933, 0.0000, 0.5363, 0.2553, 0.0000, 0.0000, 0.0000,\n        2.4420, 0.8148, 0.0000, 0.1299, 0.0000, 0.9648, 0.1002, 0.0000, 0.0000,\n        0.1953, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,\n        0.6710, 0.0000, 0.0000, 0.0363, 0.0000, 0.0000, 0.1915, 0.8561, 0.3103,\n        0.4624, 0.5061, 0.0000, 0.0000, 0.0160, 0.0000, 0.0811, 0.9417, 0.5338,\n        0.0000, 0.1866, 0.7537, 0.0000, 0.0000, 0.0294, 1.0851, 0.5546, 0.0000,\n        0.0000, 0.0000, 0.0000, 0.3004, 0.2326, 0.0000, 0.0000, 0.1175, 0.0000,\n        0.1841, 0.0923, 0.0000, 0.0000, 0.0000, 0.1905, 0.0000, 0.4160, 0.0000,\n        0.0000, 0.0000, 0.0000, 0.2005, 1.1662, 0.0000, 0.0000, 0.3233, 0.0000,\n        0.3768, 0.5544, 1.5398, 0.3858, 0.0000, 0.4407, 0.0854, 0.0000, 0.0954,\n        0.2612, 0.0828, 0.3669, 0.0000, 0.2595, 0.5530, 0.2733, 0.0969, 0.0240,\n        0.4898, 0.6570, 0.1530, 0.1105, 0.0000, 0.0213, 0.0000, 0.0000, 0.0000,\n        0.1877, 0.0000, 0.0000, 0.0000, 0.5524, 0.0801, 0.4525, 0.0000, 0.0641,\n        0.0000, 0.0893, 0.0971, 0.0000, 0.0817, 0.0000, 0.5512, 0.0000, 0.7226,\n        0.0000, 0.0000, 0.8155, 0.0000, 0.0000, 0.0000, 0.1922, 0.0000, 0.0000,\n        0.8509, 0.0000, 0.0000, 0.0530, 0.0000, 0.5781, 0.0000, 0.3034, 0.0000,\n        0.0000, 0.0000, 0.9215, 0.0000, 0.3824, 0.0000, 0.0000, 0.1984, 0.0000,\n        0.1508, 0.0384, 0.2596, 0.0000, 0.0000, 0.4147, 0.0000, 0.7621, 1.1227,\n        0.0000, 0.0000, 0.4384, 0.2036, 0.2036, 0.1319, 0.0000, 0.0000, 2.0121,\n        0.2268, 0.1649, 0.0000, 0.0000, 0.0117, 0.1656, 0.2116, 0.6669, 0.0000,\n        0.0000, 0.0190, 0.2158, 0.0000, 0.0000, 0.0000, 0.1761, 0.6894, 0.5038,\n        0.0347, 0.0000, 0.0286, 0.0000, 0.6013, 0.5798, 0.1612, 0.4469, 0.0787,\n        0.1113, 2.2523, 0.0000, 0.0000, 0.0000, 0.3400, 0.0000, 0.7689, 0.0000,\n        2.0817, 0.3160, 0.1292, 0.0000, 0.3779, 0.0000, 0.1386, 0.0000, 0.3331,\n        0.0000, 0.0000, 0.5519, 0.4768, 0.0000, 0.1587, 0.3745, 0.5183, 0.1886,\n        0.2651, 0.0000, 0.0000, 0.0000, 0.3153, 0.0463, 0.0000, 0.0000, 0.1057,\n        0.0000, 0.0000, 0.4028, 0.2373, 0.1635, 0.0000, 0.0000, 0.2426, 0.0730,\n        0.1021, 0.4884, 0.0540, 0.0000, 0.3141, 0.0000, 0.3600, 0.0000, 0.2893,\n        0.4283, 0.2972, 0.0000, 0.4827, 0.0000, 0.0000, 0.5132, 0.0000, 0.3668,\n        0.0000, 0.3252, 0.3664, 0.3555, 0.5139, 0.0000, 0.6309, 0.0000])'),
 ('FC1=CC(F)=CC=C1',

In [4]:
master_df.info()
#Identify which rows are missing embeddings
missing_embeddings = master_df["embeddings"].isna()
#Creates a new df
missing_embeddings = master_df.loc[missing_embeddings]
missing_embeddings.to_csv('missing_embeddings.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110355 entries, 0 to 110354
Data columns (total 18 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   SMILES      110355 non-null  object
 1   MP          108399 non-null  float64
 2   Type        110355 non-null  object
 3   exp MP      1956 non-null    float64
 4   GNN1        1956 non-null    float64
 5   GNN2        1956 non-null    float64
 6   GNN3        1956 non-null    float64
 7   GNN4        1956 non-null    float64
 8   GNN5        1956 non-null    float64
 9   GNN6        1956 non-null    float64
 10  GNN7        1956 non-null    float64
 11  GNN8        1956 non-null    float64
 12  GNN9        1956 non-null    float64
 13  GNN10       1956 non-null    float64
 14  Consensus   1956 non-null    float64
 15  SD          1956 non-null    float64
 16  Mpexp       0 non-null       float64
 17  embeddings  110322 non-null  object
dtypes: float64(15), object(3)
memory usage: 15.2+ MB

In [5]:
#Creates a dictionary (even if the key does not have to exist yet)
unmatched_counts = defaultdict(list)
subfolders = ["test_predictions", "train_with_data_augmentation", "train_without_data_augmentation", "val"]

In [6]:
#Loops through the folders in the test, training (both with and without augmentation) and val folders
for subfolder in subfolders:
    source_folder = source_root / subfolder
    #Builds a path to save the updated files
    target_folder = target_root / subfolder
    target_folder.mkdir(parents=True, exist_ok=True)  # Create output folders if they don't exist

    # Loop through all CSV files in the folder in original_curated, .glob matches to the .csv files
    for file in source_folder.glob("*.csv"):
        df = pd.read_csv(file)

        # Creates a new embeddings coloumn, looks at each SMILES coloumn and uses embedding_dict to match the corresponding embedding
        #Nan for missing values
        df["embeddings"] = df["SMILES"].map(embedding_dict)

        # Count how many SMILES did not have a matching embedding
        unmatched = df["embeddings"].isna().sum()
        unmatched_counts[subfolder].append((file.name, unmatched))

        # Save the updated DataFrame to the new location
        df.to_csv(target_folder / file.name, index=False)

In [7]:
#Create an empty list secreibing the folder, file and how many SMILES were unmatched
summary = []

for folder, files in unmatched_counts.items():
    for file_name, unmatched in files:
        summary.append({
            "Folder": folder,
            "File": file_name,
            "Unmatched_SMILES": unmatched
        })

unmatched_df = pd.DataFrame(summary)
unmatched_df.sort_values(by=["Folder", "Unmatched_SMILES"], ascending=[True, False], inplace=True)
unmatched_df.reset_index(drop=True, inplace=True)

# Display it nicely in a notebook
display(unmatched_df)

,Folder,File,Unmatched_SMILES
0,test_predictions,consensus_without_data_augmentation.csv,0
1,test_predictions,consensus_with_data_augmentation_curated.csv,0
2,train_with_data_augmentation,train2_DA_curated.csv,32
3,train_with_data_augmentation,train1_DA_curated.csv,32
4,train_with_data_augmentation,train6_DA_curated.csv,32
5,train_with_data_augmentation,train3_DA_curated.csv,30
6,train_with_data_augmentation,train4_DA_curated.csv,26
7,train_with_data_augmentation,train9_DA_curated.csv,24
8,train_with_data_augmentation,train5_DA_curated.csv,23
9,train_with_data_augmentation,train8_DA_curated.csv,23
10,train_with_data_augmentation,train10_DA_curated.csv,22
11,train_with_data_augmentation,train7_DA_curated.csv,12
12,train_without_data_augmentation,train6_curated.csv,0
13,train_without_data_augmentation,train3_curated.csv,0
14,train_without_data_augmentation,train10_curated.csv,0
15,train_without_data_augmentation,train9_curated.csv,0
16,train_without_data_augmentation,train5_curated.csv,0
17,train_without_data_augmentation,train2_curated.csv,0
18,train_without_data_augmentation,train7_curated.csv,0
19,train_without_data_augmentation,train4_curated.csv,0
20,train_without_data_augmentation,train8_curated.csv,0
21,train_without_data_augmentation,train1_curated.csv,0
22,val,val9_curated.csv,0
23,val,val10_curated.csv,0
24,val,val5_curated.csv,0
25,val,val6_curated.csv,0
26,val,val3_curated.csv,0
27,val,val4_curated.csv,0
28,val,val8_curated.csv,0
29,val,val1_curated.csv,0
30,val,val2_curated.csv,0
31,val,val7_curated.csv,0

In [8]:
from rdkit import Chem
from rdkit.Chem import Descriptors

def molecular_weight(smiles):
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol:
            return Descriptors.MolWt(mol)
        else:
            return None
    except:
        return None

In [9]:
BASE = Path.cwd().parent
subfolders = ["test_predictions", "train_with_data_augmentation", "train_without_data_augmentation", "val"]
target_root = BASE / "data_curation" / "original_curated_with_embeddings_and_MW"

summary = []

#Loops through the folders in the test, training (both with and without augmentation) and val folders in embeddings folder
for subfolder in subfolders:
    folder = target_root / subfolder
    if not folder.exists():
        print(f"Folder {folder} does not exist. Skipping.")
        continue
    
    # Loop through all CSV files in the folder in original_curated, .glob matches to the .csv files
    for file in folder.glob("*.csv"):
        df = pd.read_csv(file)
        # Check if the SMILES column exists
        if "SMILES" not in df.columns:
            print(f"SMILES column not found in {file.name}. Skipping.")
            continue
    
        # Creates a new molecular weight column, looks at each SMILES column and calculates the molecular weight
        df["MW"] = df["SMILES"].apply(molecular_weight).astype("Float64").round(3)

        # Overwrite the existing file with the new DataFrame
        df.to_csv(file, index=False)
        
        df.info()
        rows = len(df)
        coloumn_names = df.columns.tolist()
        missing_SMILES = int(df['SMILES'].isna().sum())
        missing_MW = int(df['MW'].isna().sum())
        missing_embeddings = int(df['embeddings'].isna().sum())
        
        summary.append({
            "Folder": subfolder,
            "File": file.name,
            "Coloumn_Names": coloumn_names,
            "Total_Rows": rows,
            "Missing_SMILES": missing_SMILES,
            "Missing_MW": missing_MW,
            "Missing_Embeddings": missing_embeddings
        })

summary_df = (
    pd.DataFrame(summary)
      .sort_values(by=["Folder"])
      .reset_index(drop=True)
) 
display(summary_df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1961 entries, 0 to 1960
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      1961 non-null   object
 1   exp MP      1961 non-null   float64
 2   GNN1        1961 non-null   float64
 3   GNN2        1961 non-null   float64
 4   GNN3        1961 non-null   float64
 5   GNN4        1961 non-null   float64
 6   GNN5        1961 non-null   float64
 7   GNN6        1961 non-null   float64
 8   GNN7        1961 non-null   float64
 9   GNN8        1961 non-null   float64
 10  GNN9        1961 non-null   float64
 11  GNN10       1961 non-null   float64
 12  Consensus   1961 non-null   float64
 13  SD          1961 non-null   float64
 14  embeddings  1961 non-null   object
 15  MW          1961 non-null   Float64
dtypes: Float64(1), float64(13), object(2)
memory usage: 247.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1961 entries, 0 to 1960
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      1961 non-null   object
 1   Mpexp       1961 non-null   float64
 2   GNN1        1961 non-null   float64
 3   GNN2        1961 non-null   float64
 4   GNN3        1961 non-null   float64
 5   GNN4        1961 non-null   float64
 6   GNN5        1961 non-null   float64
 7   GNN6        1961 non-null   float64
 8   GNN7        1961 non-null   float64
 9   GNN8        1961 non-null   float64
 10  GNN9        1961 non-null   float64
 11  GNN10       1961 non-null   float64
 12  Consensus   1961 non-null   float64
 13  SD          1961 non-null   float64
 14  embeddings  1961 non-null   object
 15  MW          1961 non-null   Float64
dtypes: Float64(1), float64(13), object(2)
memory usage: 247.2+ KB

[11:30:30] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:30:30] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:30:30] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:30:30] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:30:30] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:30:30] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:30:30] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:30:31] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:31] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:31] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:30:31] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:30:31] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:31] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:31] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:31] non-ring atom 1 marked aromatic
[11:30:31] non-ring atom 1 marked aromatic
[11:30:31] non-ring atom 1 marked aromatic
[11:30:31] non-ring atom 1 marked aromatic
[11:30:32] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:30:32] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:30:32] Explicit valence for atom # 1 C, 5, is greater than permitted
[11:30:32] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:30:32] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:30:32] Explicit valence for atom # 1 C, 5, is greater than permitted
[11:30:33] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
[11:30:33] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84439 entries, 0 to 84438
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      84439 non-null  object
 1   MP          84439 non-null  float64
 2   embeddings  84413 non-null  object
 3   MW          84413 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 2.7+ MB

[11:30:39] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:30:39] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:30:40] non-ring atom 1 marked aromatic
[11:30:40] non-ring atom 1 marked aromatic
[11:30:40] non-ring atom 1 marked aromatic
[11:30:40] non-ring atom 1 marked aromatic
[11:30:40] non-ring atom 1 marked aromatic
[11:30:42] non-ring atom 1 marked aromatic
[11:30:42] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:30:42] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:30:42] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:30:42] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:30:42] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:30:42] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:30:42] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:30:42] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:42] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:42] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:30:42] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:30:42] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:42] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:42] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:42] non-ring atom 1 marked aromatic
[11:30:42] non-ring atom 1 marked aromatic
[11:30:43] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
[11:30:43] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
[11:30:43] Explicit valence for atom # 1 C, 5, is greater than permitted
[11:30:43] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:30:43] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:30:43] Explicit valence for atom # 1 C, 5, is greater than permitted

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84772 entries, 0 to 84771
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      84772 non-null  object
 1   MP          84772 non-null  float64
 2   embeddings  84742 non-null  object
 3   MW          84742 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 2.7+ MB

[11:30:50] non-ring atom 1 marked aromatic
[11:30:50] non-ring atom 1 marked aromatic
[11:30:50] non-ring atom 1 marked aromatic
[11:30:51] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:30:51] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:30:51] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:30:51] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:30:51] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:30:51] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:30:51] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:30:51] non-ring atom 1 marked aromatic
[11:30:51] non-ring atom 1 marked aromatic
[11:30:51] non-ring atom 1 marked aromatic
[11:30:51] non-ring atom 1 marked aromatic
[11:30:51] Explicit valence for atom # 1 C, 5, is greater than permitted
[11:30:51] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:30:51] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:30:51] Explicit valence for atom # 1 C, 5, is greater than permitted
[11:30:51] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
[11:30:51] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
[11:30:52] non-ring atom 1 marked aromatic
[11:30:52] non-ring atom 1 marked aromatic
[11:30:52] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:52] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:52] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:30:52] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:30:52] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:52] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:52] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:52] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:30:52] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:30:53] SMILES Parse Error: syntax error while parsing: CNC(=C/N+](=O)[O-])NCCSCc1ccc(o1)CN(C)C
[11:30:53] SMILES Parse Error: check for mistakes around position 9:
[11:30:53] CNC(=C/N+](=O)[O-])NCCSCc1ccc(o1)CN(C)C
[11:30:53] ~~~~~~~~^
[11:30:53] SMILES Parse Error: extra open parentheses while parsing: CNC(=C/N+](=O)[O-])NCCSCc1ccc(o1)CN(C)C
[11:30:53] SMILES Parse Error: check for mistakes around position 4:
[11:30:53] CNC(=C/N+](=O)[O-])NCCSCc1ccc(o1)CN(C)C
[11:30:53] ~~~^
[11:30:53] SMILES Parse Error: Failed parsing SMILES 'CNC(=C/N+](=O)[O-])NCCSCc1ccc(o1)CN(C)C' for input: 'CNC(=C/N+](=O)[O-])NCCSCc1ccc(o1)CN(C)C'

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85072 entries, 0 to 85071
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      85072 non-null  object
 1   MP          85072 non-null  float64
 2   embeddings  85040 non-null  object
 3   MW          85040 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 2.7+ MB

[11:30:59] non-ring atom 1 marked aromatic
[11:30:59] Explicit valence for atom # 1 C, 5, is greater than permitted
[11:30:59] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:30:59] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:30:59] Explicit valence for atom # 1 C, 5, is greater than permitted
[11:30:59] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:59] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:59] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:30:59] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:30:59] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:59] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:59] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:30:59] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:30:59] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:31:00] non-ring atom 1 marked aromatic
[11:31:00] non-ring atom 1 marked aromatic
[11:31:01] non-ring atom 1 marked aromatic
[11:31:01] non-ring atom 1 marked aromatic
[11:31:02] non-ring atom 1 marked aromatic
[11:31:02] non-ring atom 1 marked aromatic
[11:31:02] non-ring atom 1 marked aromatic
[11:31:02] non-ring atom 1 marked aromatic
[11:31:02] non-ring atom 1 marked aromatic

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84504 entries, 0 to 84503
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      84504 non-null  object
 1   MP          84504 non-null  float64
 2   embeddings  84481 non-null  object
 3   MW          84481 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 2.7+ MB

[11:31:09] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:31:09] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:31:10] non-ring atom 1 marked aromatic
[11:31:10] non-ring atom 1 marked aromatic
[11:31:11] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
[11:31:11] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
[11:31:11] non-ring atom 1 marked aromatic
[11:31:11] non-ring atom 1 marked aromatic
[11:31:11] non-ring atom 1 marked aromatic
[11:31:11] non-ring atom 1 marked aromatic
[11:31:11] non-ring atom 1 marked aromatic
[11:31:11] non-ring atom 1 marked aromatic

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84765 entries, 0 to 84764
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      84765 non-null  object
 1   MP          84765 non-null  float64
 2   embeddings  84753 non-null  object
 3   MW          84753 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 2.7+ MB

[11:31:19] non-ring atom 1 marked aromatic
[11:31:19] non-ring atom 1 marked aromatic
[11:31:19] Explicit valence for atom # 1 C, 5, is greater than permitted
[11:31:19] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:31:19] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:31:19] Explicit valence for atom # 1 C, 5, is greater than permitted
[11:31:19] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:31:19] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:31:19] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:31:19] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:31:19] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:31:19] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:31:19] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:31:19] non-ring atom 1 marked aromatic
[11:31:19] non-ring atom 1 marked aromatic
[11:31:19] non-ring atom 1 marked aromatic
[11:31:20] non-ring atom 1 marked aromatic
[11:31:20] non-ring atom 1 marked aromatic
[11:31:20] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
[11:31:20] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
[11:31:21] non-ring atom 1 marked aromatic
[11:31:22] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:31:22] Explicit valence for atom # 49 C, 5, is greater than permitted

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84932 entries, 0 to 84931
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      84932 non-null  object
 1   MP          84932 non-null  float64
 2   embeddings  84909 non-null  object
 3   MW          84909 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 2.7+ MB

[11:31:29] non-ring atom 1 marked aromatic
[11:31:29] non-ring atom 1 marked aromatic
[11:31:29] non-ring atom 1 marked aromatic
[11:31:29] non-ring atom 1 marked aromatic
[11:31:29] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:31:29] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:31:29] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:31:29] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:31:29] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:31:29] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:31:29] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:31:30] non-ring atom 1 marked aromatic
[11:31:30] non-ring atom 1 marked aromatic
[11:31:32] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:31:32] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:31:32] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:31:32] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:31:32] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:31:32] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:31:32] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:31:32] non-ring atom 1 marked aromatic
[11:31:32] non-ring atom 1 marked aromatic
[11:31:32] non-ring atom 1 marked aromatic
[11:31:32] non-ring atom 1 marked aromatic

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84956 entries, 0 to 84955
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      84956 non-null  object
 1   MP          84956 non-null  float64
 2   embeddings  84932 non-null  object
 3   MW          84932 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 2.7+ MB

[11:31:39] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:31:39] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:31:39] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:31:39] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:31:39] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:31:39] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:31:39] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:31:39] non-ring atom 1 marked aromatic
[11:31:39] non-ring atom 1 marked aromatic
[11:31:39] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:31:39] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:31:39] non-ring atom 1 marked aromatic
[11:31:39] non-ring atom 1 marked aromatic
[11:31:40] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
[11:31:40] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
[11:31:40] non-ring atom 1 marked aromatic
[11:31:40] non-ring atom 1 marked aromatic
[11:31:40] non-ring atom 1 marked aromatic
[11:31:40] non-ring atom 1 marked aromatic
[11:31:41] non-ring atom 1 marked aromatic
[11:31:42] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:31:42] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:31:42] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:31:42] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:31:42] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:31:42] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:31:42] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:31:42] non-ring atom 1 marked aromatic
[11:31:42] Explicit valence for atom # 1 C, 5, is greater than permitted
[11:31:42] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:31:42] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:31:42] Explicit valence for atom # 1 C, 5, is greater than permitted

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85439 entries, 0 to 85438
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      85439 non-null  object
 1   MP          85439 non-null  float64
 2   embeddings  85407 non-null  object
 3   MW          85407 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 2.7+ MB

[11:31:49] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
[11:31:49] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
[11:31:49] non-ring atom 1 marked aromatic
[11:31:49] non-ring atom 1 marked aromatic
[11:31:49] non-ring atom 1 marked aromatic
[11:31:49] non-ring atom 1 marked aromatic
[11:31:50] non-ring atom 1 marked aromatic
[11:31:50] non-ring atom 1 marked aromatic
[11:31:50] non-ring atom 1 marked aromatic
[11:31:51] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:31:51] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:31:51] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:31:51] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:31:51] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:31:51] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:31:51] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:31:51] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:31:51] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:31:52] Explicit valence for atom # 1 C, 5, is greater than permitted
[11:31:52] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:31:52] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:31:52] Explicit valence for atom # 1 C, 5, is greater than permitted

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84732 entries, 0 to 84731
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      84732 non-null  object
 1   MP          84732 non-null  float64
 2   embeddings  84710 non-null  object
 3   MW          84710 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 2.7+ MB

[11:31:59] non-ring atom 1 marked aromatic
[11:31:59] non-ring atom 1 marked aromatic
[11:31:59] Explicit valence for atom # 1 C, 5, is greater than permitted
[11:31:59] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:31:59] Explicit valence for atom # 6 C, 5, is greater than permitted
[11:31:59] Explicit valence for atom # 1 C, 5, is greater than permitted
[11:31:59] non-ring atom 1 marked aromatic
[11:31:59] non-ring atom 1 marked aromatic
[11:32:00] non-ring atom 1 marked aromatic
[11:32:00] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:32:00] Explicit valence for atom # 49 C, 5, is greater than permitted
[11:32:00] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
[11:32:00] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
[11:32:01] non-ring atom 1 marked aromatic
[11:32:01] non-ring atom 1 marked aromatic
[11:32:01] non-ring atom 1 marked aromatic
[11:32:01] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:32:01] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:32:01] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:32:01] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:32:01] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:32:01] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:32:01] Explicit valence for atom # 3 O, 3, is greater than permitted
[11:32:02] non-ring atom 1 marked aromatic
[11:32:02] non-ring atom 1 marked aromatic
[11:32:02] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:32:02] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:32:02] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:32:02] Explicit valence for atom # 4 C, 5, is greater than permitted
[11:32:02] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:32:02] Explicit valence for atom # 1 O, 3, is greater than permitted
[11:32:02] Explicit valence for atom # 1 O, 3, is greater than permitted

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85225 entries, 0 to 85224
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      85225 non-null  object
 1   MP          85225 non-null  float64
 2   embeddings  85193 non-null  object
 3   MW          85193 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 2.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13734 entries, 0 to 13733
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      13734 non-null  object
 1   MP          13734 non-null  float64
 2   embeddings  13734 non-null  object
 3   MW          13734 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 442.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13734 entries, 0 to 13733
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      13734 non-null  object
 1   MP          13734 non-null  float64
 2   embeddings  13734 non-null  object
 3   MW          13734 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 442.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13734 entries, 0 to 13733
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      13734 non-null  object
 1   MP          13734 non-null  float64
 2   embeddings  13734 non-null  object
 3   MW          13734 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 442.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13734 entries, 0 to 13733
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      13734 non-null  object
 1   MP          13734 non-null  float64
 2   embeddings  13734 non-null  object
 3   MW          13734 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 442.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13734 entries, 0 to 13733
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      13734 non-null  object
 1   MP          13734 non-null  float64
 2   embeddings  13734 non-null  object
 3   MW          13734 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 442.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13734 entries, 0 to 13733
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      13734 non-null  object
 1   MP          13734 non-null  float64
 2   embeddings  13734 non-null  object
 3   MW          13734 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 442.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13734 entries, 0 to 13733
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      13734 non-null  object
 1   MP          13734 non-null  float64
 2   embeddings  13734 non-null  object
 3   MW          13734 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 442.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13734 entries, 0 to 13733
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      13734 non-null  object
 1   MP          13734 non-null  float64
 2   embeddings  13734 non-null  object
 3   MW          13734 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 442.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13734 entries, 0 to 13733
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      13734 non-null  object
 1   MP          13734 non-null  float64
 2   embeddings  13734 non-null  object
 3   MW          13734 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 442.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13734 entries, 0 to 13733
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      13734 non-null  object
 1   MP          13734 non-null  float64
 2   embeddings  13734 non-null  object
 3   MW          13734 non-null  Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 442.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      3925 non-null   object
 1   MP          3925 non-null   float64
 2   embeddings  3925 non-null   object
 3   MW          3925 non-null   Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 126.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      3925 non-null   object
 1   MP          3925 non-null   float64
 2   embeddings  3925 non-null   object
 3   MW          3925 non-null   Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 126.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      3925 non-null   object
 1   MP          3925 non-null   float64
 2   embeddings  3925 non-null   object
 3   MW          3925 non-null   Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 126.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      3925 non-null   object
 1   MP          3925 non-null   float64
 2   embeddings  3925 non-null   object
 3   MW          3925 non-null   Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 126.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      3925 non-null   object
 1   MP          3925 non-null   float64
 2   embeddings  3925 non-null   object
 3   MW          3925 non-null   Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 126.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      3925 non-null   object
 1   MP          3925 non-null   float64
 2   embeddings  3925 non-null   object
 3   MW          3925 non-null   Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 126.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      3925 non-null   object
 1   MP          3925 non-null   float64
 2   embeddings  3925 non-null   object
 3   MW          3925 non-null   Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 126.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      3925 non-null   object
 1   MP          3925 non-null   float64
 2   embeddings  3925 non-null   object
 3   MW          3925 non-null   Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 126.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      3925 non-null   object
 1   MP          3925 non-null   float64
 2   embeddings  3925 non-null   object
 3   MW          3925 non-null   Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 126.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SMILES      3925 non-null   object
 1   MP          3925 non-null   float64
 2   embeddings  3925 non-null   object
 3   MW          3925 non-null   Float64
dtypes: Float64(1), float64(1), object(2)
memory usage: 126.6+ KB

,Folder,File,Coloumn_Names,Total_Rows,Missing_SMILES,Missing_MW,Missing_Embeddings
0,test_predictions,consensus_without_data_augmentation.csv,"[SMILES, exp MP, GNN1, GNN2, GNN3, GNN4, GNN5,...",1961,0,0,0
1,test_predictions,consensus_with_data_augmentation_curated.csv,"[SMILES, Mpexp, GNN1, GNN2, GNN3, GNN4, GNN5, ...",1961,0,0,0
2,train_with_data_augmentation,train6_DA_curated.csv,"[SMILES, MP, embeddings, MW]",85225,0,32,32
3,train_with_data_augmentation,train10_DA_curated.csv,"[SMILES, MP, embeddings, MW]",84732,0,22,22
4,train_with_data_augmentation,train1_DA_curated.csv,"[SMILES, MP, embeddings, MW]",85439,0,32,32
5,train_with_data_augmentation,train8_DA_curated.csv,"[SMILES, MP, embeddings, MW]",84932,0,23,23
6,train_with_data_augmentation,train9_DA_curated.csv,"[SMILES, MP, embeddings, MW]",84956,0,24,24
7,train_with_data_augmentation,train5_DA_curated.csv,"[SMILES, MP, embeddings, MW]",84504,0,23,23
8,train_with_data_augmentation,train2_DA_curated.csv,"[SMILES, MP, embeddings, MW]",85072,0,32,32
9,train_with_data_augmentation,train3_DA_curated.csv,"[SMILES, MP, embeddings, MW]",84772,0,30,30
10,train_with_data_augmentation,train4_DA_curated.csv,"[SMILES, MP, embeddings, MW]",84439,0,26,26
11,train_with_data_augmentation,train7_DA_curated.csv,"[SMILES, MP, embeddings, MW]",84765,0,12,12
12,train_without_data_augmentation,train7_curated.csv,"[SMILES, MP, embeddings, MW]",13734,0,0,0
13,train_without_data_augmentation,train1_curated.csv,"[SMILES, MP, embeddings, MW]",13734,0,0,0
14,train_without_data_augmentation,train8_curated.csv,"[SMILES, MP, embeddings, MW]",13734,0,0,0
15,train_without_data_augmentation,train4_curated.csv,"[SMILES, MP, embeddings, MW]",13734,0,0,0
16,train_without_data_augmentation,train2_curated.csv,"[SMILES, MP, embeddings, MW]",13734,0,0,0
17,train_without_data_augmentation,train9_curated.csv,"[SMILES, MP, embeddings, MW]",13734,0,0,0
18,train_without_data_augmentation,train10_curated.csv,"[SMILES, MP, embeddings, MW]",13734,0,0,0
19,train_without_data_augmentation,train3_curated.csv,"[SMILES, MP, embeddings, MW]",13734,0,0,0
20,train_without_data_augmentation,train6_curated.csv,"[SMILES, MP, embeddings, MW]",13734,0,0,0
21,train_without_data_augmentation,train5_curated.csv,"[SMILES, MP, embeddings, MW]",13734,0,0,0
22,val,val2_curated.csv,"[SMILES, MP, embeddings, MW]",3925,0,0,0
23,val,val9_curated.csv,"[SMILES, MP, embeddings, MW]",3925,0,0,0
24,val,val10_curated.csv,"[SMILES, MP, embeddings, MW]",3925,0,0,0
25,val,val5_curated.csv,"[SMILES, MP, embeddings, MW]",3925,0,0,0
26,val,val6_curated.csv,"[SMILES, MP, embeddings, MW]",3925,0,0,0
27,val,val3_curated.csv,"[SMILES, MP, embeddings, MW]",3925,0,0,0
28,val,val4_curated.csv,"[SMILES, MP, embeddings, MW]",3925,0,0,0
29,val,val8_curated.csv,"[SMILES, MP, embeddings, MW]",3925,0,0,0
30,val,val1_curated.csv,"[SMILES, MP, embeddings, MW]",3925,0,0,0
31,val,val7_curated.csv,"[SMILES, MP, embeddings, MW]",3925,0,0,0

In [10]:
summary_df.to_csv('df_info.csv', index=False)